name: simplerestic
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.29.2'

dependencies:
  bloc: ^9.0.0
  equatable: ^2.0.7
  file_picker: ^9.2.3
  flutter:
    sdk: flutter

  flutter_bloc: ^9.1.1
  handy_window: ^0.4.0
  intl: ^0.20.2
  path: ^1.9.1
  path_provider: ^2.1.5
  proper_filesize: ^1.0.2
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.3.5
  tuple: ^2.0.2
  yaru: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
